### ISSUE TITLE
javah not found

### ISSUE THREAD

**Issue by HynekPetrak** [vmware/lightwave#44]
Hi,

while running bootstrapping on the current Photon, I get configure errors:
- javah is not available
configure: error: DCERPC IDL compiler not found

**Comment by gerrit-lightwave** [comment]
Hi Hynek:

To build lightwave source, please do this:
wget https://github.com/evo-cloud/hmake/releases/download/v1.3.1/hmake-linux-amd64.tar.gz
tar xvzf hmake-linux-amd64.tar.gz
chmod +x hmake
# Optional - to make available across the system
mv hmake /usr/local/bin

Then at the top Lightwave source directory, run "hmake" to build Lightwave packages.

Hope this help.  We will update README soon to replace out-dated instructions.

--Sung

________________________________

**Comment by HynekPetrak** [comment]
Thank you, that worked a bit, however I get an error later:
'''
[build-lightwave-photon2]              Using classpath ../../../vmafd/authentication-framework/packages
[build-lightwave-photon2]              /usr/bin/javac -o vecsjni.h -classpath ../../../vmafd/authentication-framework/packages/vmware-endpoint-certificate-store.jar com.vmware.identity.vecs.VecsAdapter
[build-lightwave-photon2]              javac: invalid flag: -o
[build-lightwave-photon2]              Usage: javac <options> <source files>
'''

**Comment by gerrit-lightwave** [comment]
Hmm, I don't see this error.
I got -
[build-lightwave-photon2]              make[3]: Entering directory '/src/build/vmafd/interop/jni'
[build-lightwave-photon2]              Using classpath ../../../vmafd/authentication-framework/packages
[build-lightwave-photon2]              /usr/bin/javah -o vecsjni.h -classpath ../../../vmafd/authentication-framework/packages/vmware-endpoint-certificate-store.jar com.vmware.identity.vecs.VecsAdapter
[build-lightwave-photon2]              make  all-am
[build-lightwave-photon2]              make[4]: Entering directory '/src/build/vmafd/interop/jni'

Not clear why your build try to use javac instead of javah.
What is the OS of your build machine?

--Sung
________________________________

**Comment by HynekPetrak** [comment]
Kali rolling. Which package is javah from?

**Comment by HynekPetrak** [comment]
Finally I installed openjdk-8-jdk-headless, which installs javah. Apparently javah has been removed from recent jdk releases.
